export const EXTERNAL_SUPABASE_URL = "https://hblmmmcdafnwhzyweeym.supabase.co";

export const EXTERNAL_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibG1tbWNkYWZud2h6eXdlZXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyNzk5ODksImV4cCI6MjEwMzg1NTk4OX0.L-szVm0eSSJd2tTPgM2fCXIqhVHLVdMNfNn4yKptYLE";